repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-toml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: 'https://github.com/psf/black'
    rev: 24.10.0
    hooks:
      - id: black

  - repo: 'https://github.com/pycqa/isort'
    rev: 6.1.0
    hooks:
      - id: isort
        name: isort (python)

  - repo: local
    hooks:
      - id: mypy
        name: Mypy (in Venv)
        entry: mypy
        language: python
        types: [python]
        exclude: ^tests/|^docs/
        require_serial: true
