"""index complainer_id

Revision ID: c45bedcc7fa1
Revises: 822fdda8d8d8
Create Date: 2023-02-18 13:18:48.748049

"""
from __future__ import annotations

from alembic import op

# revision identifiers, used by Alembic.
revision = "c45bedcc7fa1"
down_revision = "822fdda8d8d8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("complaint", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_complaint_complainer_id"),
            ["complainer_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("complaint", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_complaint_complainer_id"))

    # ### end Alembic commands ###
