"""Initial

Revision ID: f62fea463ca8
Revises:
Create Date: 2023-02-11 15:37:05.040506

"""
from __future__ import annotations

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = "f62fea463ca8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "first_name",
            sqlmodel.sql.sqltypes.AutoString(length=200),
            nullable=True,
        ),
        sa.Column(
            "last_name",
            sqlmodel.sql.sqltypes.AutoString(length=200),
            nullable=True,
        ),
        sa.Column(
            "phone", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True
        ),
        sa.Column(
            "role",
            sa.Enum("APPROVER", "COMPLAINER", "ADMIN", name="role"),
            server_default="COMPLAINER",
            nullable=False,
        ),
        sa.Column(
            "iban", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "password",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.UniqueConstraint("email", name=op.f("uq_user_email")),
    )
    op.create_table(
        "complaint",
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "title",
            sqlmodel.sql.sqltypes.AutoString(length=120),
            nullable=False,
        ),
        sa.Column(
            "photo_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "APPROVED", "REJECTED", name="complaintstatus"),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("complainer_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["complainer_id"],
            ["user.id"],
            name=op.f("fk_complaint_complainer_id_user"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_complaint")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("complaint")
    op.drop_table("user")
    complaint_enum = sa.Enum(name="complaintstatus")
    complaint_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
