"""amount is a monetary field

Revision ID: f88dc6c095bb
Revises: c45bedcc7fa1
Create Date: 2023-02-19 16:12:16.925408

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f88dc6c095bb"
down_revision = "c45bedcc7fa1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("complaint", schema=None) as batch_op:
        batch_op.alter_column(
            "amount",
            existing_type=sa.Float(),
            type_=sa.Numeric(precision=19, scale=4),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("complaint", schema=None) as batch_op:
        batch_op.alter_column(
            "amount",
            existing_type=sa.Numeric(precision=19, scale=4),
            type_=sa.Float(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
